ecomerce/cart/urls.py
from django.urls import path
from .views import cart_detail, cart_add, cart_remove

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='detail'),
    path("add/<int:product_id>/", cart_add, name="add"),
    path("remove/<int:product_id>/", cart_remove, name="remove"),
]

ecomerce/lojatech/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('cart/', include('cart.urls')),
    path("orders/", include("orders.urls")),
    path('products/', include('products.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

ecomerce/orders/urls.py
from django.urls import path

from .views import OrderCreateView

app_name = 'orders'

urlpatterns = [
    path('create/', OrderCreateView.as_view(), name='create'),
]

ecomerce/products/urls.py
from django.urls import path

from .views import ProductDetailView, ProductListView

app_name = "products"

urlpatterns = [
    path("", ProductListView.as_view(), name="list"),
    path("<slug:slug>/", ProductDetailView.as_view(), name="detail"),
    path("category/<slug:slug>/", ProductListView.as_view(), name="list_by_category"),
]

ecomerce/cart/forms.py
from django import forms
from django.conf import settings

PRODUCT_QUANTITY_CHOICES = [
    (i, str(i)) for i in range(1, settings.CART_ITEM_MAX_QUANTITY + 1)
]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        label="Quantidade", choices=PRODUCT_QUANTITY_CHOICES, coerce=int
    )
    override = forms.BooleanField(
        required=False, initial=False, widget=forms.HiddenInput
    )

ecomerce/cart/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_POST

from products.models import Product

from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)

    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(
            product=product, quantity=cd["quantity"], override_quantity=cd["override"]
        )

    return redirect("cart:detail")


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect("cart:detail")


def cart_detail(request):
    cart = Cart(request)
    return render(request, "cart/cart_detail.html", {"cart": cart})

ecomerce/templates/cart/cart_detail.html
{% extends 'base.html' %}

{% load static %}
{% load widget_tweaks %}

{% block title %}Meu Carrinho{% endblock title %}

{% block content %}

<div class="container table-responsive">
    <h1 class="font-weight-bold">Meu Carrinho</h1>
    {% if cart %}
    <table class="table">
        <thead>
            <tr class="bg-light">
                <th scope="col">Produto</th>
                <th scope="col">Quantidade</th>
                <th scope="col">Preço Unitário</th>
                <th scope="col">Preço Total</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            {% for item in cart %}
            {% with product=item.product %}
            <tr>
                <td class="align-middle col-md-5">
                    <a target="_blank" class="text-decoration-none" href="{{ product.get_absolute_url }}">
                        {{ product.name }}
                    </a>
                </td>
                <td class="align-middle">
                    <form action="{% url 'cart:add' product.id %}" method="post">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="col">
                                {% render_field item.update_quantity_form.quantity class+="form-control" %}
                            </div>
                            <div class="d-grid gap-2">
                                <button class="btn btn-info " type="submit" >
                                    Atualizar
                                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-arrow-clockwise" viewBox="0 0 16 16">
                                      <path fill-rule="evenodd" d="M8 3a5 5 0 1 0 4.546 2.914.5.5 0 0 1 .908-.417A6 6 0 1 1 8 2v1z"/>
                                      <path d="M8 4.466V.534a.25.25 0 0 1 .41-.192l2.36 1.966c.12.1.12.284 0 .384L8.41 4.658A.25.25 0 0 1 8 4.466z"/>
                                    </svg>
                                </button>
                            </div>
                        </div>
                        {{ item.update_quantity_form.override }}
                    </form>
                </td>
                <td class="align-middle">R$ {{ item.price }}</td>
                <td class="align-middle">R$ {{ item.total_price }}</td>
                <td class="align-middle text-right">
                    <form action="{% url 'cart:remove' product.id %}" method="post">
                        {% csrf_token %}
                        <div >
                            <button class="btn btn-danger" type="submit">
                                Excluir
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                  <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                  <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                </svg>
                            </button>
                        </div>
                    </form>
                </td>
            </tr>
            {% endwith %}
            {% endfor %}
            <tr class="bg-light">
                <td class="font-weight-bold">Total</td>
                <td></td>
                <td></td>
                <td class="font-weight-bold">R$ {{ cart.get_total_price }}</td>
                <td></td>
            </tr>

        </tbody>
    </table>
    {% else %}
    <p>O carrinho está vazio!</p>
    {% endif %}
    <p class="text-right">
        <a class=" btn btn-primary" href="{% url 'products:list' %}">
            Continuar comprando
        </a>

        <a class="btn btn-success {% if not cart %}disabled{% endif %}" href="{% url 'orders:create' %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-check-circle" viewBox="0 0 16 16">
              <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
              <path d="M10.97 4.97a.235.235 0 0 0-.02.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-1.071-1.05z"/>
            </svg>
            Finalizar compra
        </a>
    </p>
</div>

{% endblock content %}